export const INFLUENCER_CATEGORIES = [
    'Fashion',
    'Beauty',
    'Tech',
    'Gaming',
    'Fitness',
    'Travel',
    'Food',
    'Lifestyle',
    'Education',
    'Finance',
    'Parenting',
    'Art',
    'Music',
    'Entertainment',
    'Business',
    'Health',
    'Sports',
    'Photography',
    'DIY',
    'Comedy',
    'Real Estate',
    'Automotive',
    'Sustainability',
    'Pets',
    'Interior Design'
] as const;
